name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify html file exists
        run: test -f index.html

      - name: Verify css file exists
        run: test -f style.css

      - name: Verify js file exists
        run: test -f script.js

      - name: CI successful
        run: echo "Website Passed Validation!"